import 'package:flutter/material.dart';

/// Application localizations delegate
/// Generated by Flutter's l10n tool
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      AppLocalizationsDelegate();

  // Generated methods will be here
  // For now, using manual implementation

  String get appTitle => _getString('appTitle', 'SnapBeam');
  String get tagline => _getString('tagline', 'Send moments. Instantly live on your loved one\'s home screen.');
  String get welcomeTitle => _getString('welcomeTitle', 'Welcome to SnapBeam');
  String get createConnection => _getString('createConnection', 'Create Connection');
  String get joinConnection => _getString('joinConnection', 'Join Connection');
  String get enterCode => _getString('enterCode', 'Enter Connection Code');
  String get yourCode => _getString('yourCode', 'Your Connection Code');
  String get shareCode => _getString('shareCode', 'Share Code');
  String get takePhoto => _getString('takePhoto', 'Take Photo');
  String get sendPhoto => _getString('sendPhoto', 'Send Photo');
  String get addCaption => _getString('addCaption', 'Add a caption...');
  String get settings => _getString('settings', 'Settings');
  String get theme => _getString('theme', 'Theme');
  String get lightTheme => _getString('lightTheme', 'Light');
  String get darkTheme => _getString('darkTheme', 'Dark');
  String get systemTheme => _getString('systemTheme', 'System');
  String get language => _getString('language', 'Language');
  String get disconnect => _getString('disconnect', 'Disconnect');
  String get regenerateCode => _getString('regenerateCode', 'Regenerate Code');
  String get photoSent => _getString('photoSent', 'Photo sent successfully!');
  String get photoReceived => _getString('photoReceived', 'New photo received!');
  String get connectionCreated => _getString('connectionCreated', 'Connection created!');
  String get connectionJoined => _getString('connectionJoined', 'Connected successfully!');
  String get errorOccurred => _getString('errorOccurred', 'An error occurred');
  String get invalidCode => _getString('invalidCode', 'Invalid connection code');
  String get noConnection => _getString('noConnection', 'No active connection');
  String get lastUpdated => _getString('lastUpdated', 'Last updated');
  String get waitingForPhoto => _getString('waitingForPhoto', 'Waiting for first photo...');
  String get gallery => _getString('gallery', 'Gallery');
  String get camera => _getString('camera', 'Camera');
  String get cancel => _getString('cancel', 'Cancel');
  String get confirm => _getString('confirm', 'Confirm');
  String get widgetSetup => _getString('widgetSetup', 'Widget Setup');
  String get widgetInstructions => _getString('widgetInstructions', 'Add the SnapBeam widget to your home screen to see photos from your loved ones instantly.');
  String get aboutSnapbeam => _getString('aboutSnapbeam', 'About SnapBeam');
  String get version => _getString('version', 'Version');

  String _getString(String key, String defaultValue) {
    // In production, this would load from arb files
    // For now, return default values
    return defaultValue;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar', 'es'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
